// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.VaeronLogs;

/// <summary>
/// 系統存取紀錄
/// </summary>
[Table("access_records", Schema = "dbo")]
[Index("created_at", Name = "idx_access_records_created_at", AllDescending = true)]
[Index("ip_address", Name = "idx_access_records_ip_address")]
[Index("log_type", Name = "idx_access_records_log_type")]
[Index("user_id", Name = "idx_access_records_user_id")]
public partial class access_record
{
    [Key]
    public Guid id { get; set; }

    public DateTime created_at { get; set; }

    public DateTime updated_at { get; set; }

    /// <summary>
    /// 紀錄類型，例如 authorize、request、blocked
    /// </summary>
    public string log_type { get; set; } = null!;

    public string? user_id { get; set; }

    public string? created_user_name { get; set; }

    public string? ip_address { get; set; }

    public string? user_agent { get; set; }

    public string? request_path { get; set; }

    public string? request_method { get; set; }

    public int? response_status { get; set; }

    /// <summary>
    /// 額外資料 JSON
    /// </summary>
    [Column(TypeName = "jsonb")]
    public string? extra { get; set; }
}
