// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.VaeronLogs;

/// <summary>
/// 封鎖 IP 清單
/// </summary>
[Table("blocked_ips", Schema = "dbo")]
[Index("ip_address", Name = "idx_blocked_ips_ip_address", IsUnique = true)]
public partial class blocked_ip
{
    [Key]
    public Guid id { get; set; }

    public DateTime created_at { get; set; }

    public DateTime updated_at { get; set; }

    /// <summary>
    /// 被封鎖的 IP
    /// </summary>
    public string ip_address { get; set; } = null!;

    /// <summary>
    /// 封鎖原因
    /// </summary>
    public string? reason { get; set; }

    public string? created_user_name { get; set; }
}
