// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.VaeronLogs;

/// <summary>
/// 系統錯誤日誌
/// </summary>
[Table("error_logs", Schema = "dbo")]
[Index("created_at", Name = "idx_error_logs_created_at", AllDescending = true)]
[Index("layer", Name = "idx_error_logs_layer")]
[Index("status_code", Name = "idx_error_logs_status_code")]
[Index("trace_id", Name = "idx_error_logs_trace_id")]
[Index("user_id", Name = "idx_error_logs_user_id")]
public partial class error_log
{
    [Key]
    public Guid id { get; set; }

    public DateTime created_at { get; set; }

    /// <summary>
    /// 錯誤所在層級
    /// </summary>
    public string? layer { get; set; }

    /// <summary>
    /// 錯誤階段
    /// </summary>
    public int? stage { get; set; }

    /// <summary>
    /// 方法名稱
    /// </summary>
    public string? function_name { get; set; }

    /// <summary>
    /// 完整方法路徑
    /// </summary>
    public string? function_full { get; set; }

    public string? message { get; set; }

    public string? stack_trace { get; set; }

    public string? path { get; set; }

    public string? http_method { get; set; }

    public int? status_code { get; set; }

    public string? trace_id { get; set; }

    public string? user_id { get; set; }

    /// <summary>
    /// 額外錯誤資料 JSON
    /// </summary>
    [Column(TypeName = "jsonb")]
    public string? extra { get; set; }
}
