// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Models.VaeronLogs;

public partial class VaeronLogsDbContext : DbContext
{
    public VaeronLogsDbContext(DbContextOptions<VaeronLogsDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<access_record> access_records { get; set; }

    public virtual DbSet<blocked_ip> blocked_ips { get; set; }

    public virtual DbSet<error_log> error_logs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<access_record>(entity =>
        {
            entity.HasKey(e => e.id).HasName("access_records_pkey");

            entity.ToTable("access_records", "dbo", tb => tb.HasComment("系統存取紀錄"));

            entity.Property(e => e.id).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
            entity.Property(e => e.extra).HasComment("額外資料 JSON");
            entity.Property(e => e.log_type)
                .HasDefaultValueSql("'authorize'::text")
                .HasComment("紀錄類型，例如 authorize、request、blocked");
            entity.Property(e => e.updated_at).HasDefaultValueSql("now()");
        });

        modelBuilder.Entity<blocked_ip>(entity =>
        {
            entity.HasKey(e => e.id).HasName("blocked_ips_pkey");

            entity.ToTable("blocked_ips", "dbo", tb => tb.HasComment("封鎖 IP 清單"));

            entity.Property(e => e.id).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
            entity.Property(e => e.ip_address).HasComment("被封鎖的 IP");
            entity.Property(e => e.reason).HasComment("封鎖原因");
            entity.Property(e => e.updated_at).HasDefaultValueSql("now()");
        });

        modelBuilder.Entity<error_log>(entity =>
        {
            entity.HasKey(e => e.id).HasName("error_logs_pkey");

            entity.ToTable("error_logs", "dbo", tb => tb.HasComment("系統錯誤日誌"));

            entity.Property(e => e.id).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
            entity.Property(e => e.extra).HasComment("額外錯誤資料 JSON");
            entity.Property(e => e.function_full).HasComment("完整方法路徑");
            entity.Property(e => e.function_name).HasComment("方法名稱");
            entity.Property(e => e.layer).HasComment("錯誤所在層級");
            entity.Property(e => e.stage).HasComment("錯誤階段");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
