// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.Hnb;

[Table("access_records", Schema = "dbo")]
public partial class access_record
{
    [Key]
    public Guid id { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? created_at { get; set; }

    public string? log_type { get; set; }

    public string? user_id { get; set; }

    public string? ip_address { get; set; }

    public string? user_agent { get; set; }

    public string? request_path { get; set; }

    public string? request_method { get; set; }

    public int? response_status { get; set; }

    public string? created_user_name { get; set; }
}
