// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.Hnb;

[Table("error_logs", Schema = "dbo")]
public partial class error_log
{
    [Key]
    public Guid id { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? created_at { get; set; }

    public string? layer { get; set; }

    public int? stage { get; set; }

    public string? function { get; set; }

    public string? function_full { get; set; }

    public string? message { get; set; }

    public string? stack_trace { get; set; }

    public string? path { get; set; }

    public string? http_method { get; set; }

    public int? status_code { get; set; }

    public string? trace_id { get; set; }

    public string? user_id { get; set; }

    public string? extra { get; set; }
}
