// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Net;
using Microsoft.EntityFrameworkCore;

namespace HNB.IIS.Core.Models.HnbHnbBackoffice;

/// <summary>
/// 權限管理統一資料表 - 用於統一管理用戶、角色、組織三種類型的資料，透過 type 欄位區分資料類型
/// </summary>
[Table("permission_management", Schema = "dbo")]
[Index("created_at", Name = "idx_permission_management_created_at")]
[Index("email", Name = "idx_permission_management_email")]
[Index("is_active", Name = "idx_permission_management_is_active")]
[Index("last_login_at", Name = "idx_permission_management_last_login_at")]
[Index("login_method", Name = "idx_permission_management_login_method")]
[Index("parent_id", Name = "idx_permission_management_parent_id")]
[Index("status", Name = "idx_permission_management_status")]
[Index("subscription_status", Name = "idx_permission_management_subscription_status")]
[Index("third_party_id", Name = "idx_permission_management_third_party_id")]
[Index("type", Name = "idx_permission_management_type")]
public partial class permission_management
{
    /// <summary>
    /// 主鍵ID
    /// </summary>
    [Key]
    public int id { get; set; }

    /// <summary>
    /// 資料類型：user=用戶, role=角色, organization=組織
    /// </summary>
    [StringLength(50)]
    public string type { get; set; } = null!;

    /// <summary>
    /// 名稱：用戶=username, 角色=角色名稱, 組織=組織名稱
    /// </summary>
    [StringLength(100)]
    public string name { get; set; } = null!;

    /// <summary>
    /// 描述：角色或組織的詳細說明
    /// </summary>
    [StringLength(500)]
    public string? description { get; set; }

    /// <summary>
    /// 電子郵件：主要用於用戶登入和聯絡
    /// </summary>
    [StringLength(255)]
    public string? email { get; set; }

    /// <summary>
    /// 電話號碼：用戶聯絡電話
    /// </summary>
    [StringLength(20)]
    public string? phone { get; set; }

    /// <summary>
    /// 個人簡介：用戶的自我介紹
    /// </summary>
    public string? bio { get; set; }

    /// <summary>
    /// 頭像網址：用戶頭像圖片連結
    /// </summary>
    [StringLength(500)]
    public string? avatar_url { get; set; }

    /// <summary>
    /// 暱稱：用戶的顯示暱稱
    /// </summary>
    [StringLength(100)]
    public string? nickname { get; set; }

    /// <summary>
    /// 完整名稱：用戶=真實姓名, 角色=角色完整名稱, 組織=組織完整名稱
    /// </summary>
    [StringLength(200)]
    public string? full_name { get; set; }

    /// <summary>
    /// 性別：男/女/其他
    /// </summary>
    [StringLength(10)]
    public string? gender { get; set; }

    /// <summary>
    /// 生日：用戶出生日期
    /// </summary>
    public DateOnly? birthday { get; set; }

    /// <summary>
    /// 星座：用戶星座
    /// </summary>
    [StringLength(20)]
    public string? zodiac_sign { get; set; }

    /// <summary>
    /// 喜愛的顏色：用戶偏好顏色
    /// </summary>
    [StringLength(50)]
    public string? favorite_color { get; set; }

    /// <summary>
    /// 色彩主題：用戶介面色彩配置
    /// </summary>
    [StringLength(50)]
    public string? color_scheme { get; set; }

    /// <summary>
    /// 所在地：用戶居住或工作地點
    /// </summary>
    [StringLength(200)]
    public string? location { get; set; }

    /// <summary>
    /// 時區：用戶所在時區
    /// </summary>
    [StringLength(50)]
    public string? timezone { get; set; }

    /// <summary>
    /// 密碼雜湊值：用於用戶密碼驗證
    /// </summary>
    [StringLength(255)]
    public string? password_hash { get; set; }

    /// <summary>
    /// 密碼鹽值：用於密碼雜湊的隨機字串
    /// </summary>
    [StringLength(255)]
    public string? salt { get; set; }

    /// <summary>
    /// 登入方式：local/oauth/google/facebook等
    /// </summary>
    [StringLength(50)]
    public string? login_method { get; set; }

    /// <summary>
    /// 第三方ID：OAuth等第三方登入的用戶ID
    /// </summary>
    [StringLength(255)]
    public string? third_party_id { get; set; }

    /// <summary>
    /// 第三方郵箱：第三方登入的郵箱地址
    /// </summary>
    [StringLength(255)]
    public string? third_party_email { get; set; }

    /// <summary>
    /// 第三方頭像：第三方登入的頭像網址
    /// </summary>
    [StringLength(500)]
    public string? third_party_avatar { get; set; }

    /// <summary>
    /// 郵箱是否驗證：true=已驗證, false=未驗證
    /// </summary>
    public bool? is_email_verified { get; set; }

    /// <summary>
    /// 電話是否驗證：true=已驗證, false=未驗證
    /// </summary>
    public bool? is_phone_verified { get; set; }

    /// <summary>
    /// 是否啟用雙因子認證：true=啟用, false=未啟用
    /// </summary>
    public bool? two_factor_enabled { get; set; }

    /// <summary>
    /// 雙因子認證密鑰：TOTP密鑰
    /// </summary>
    [StringLength(255)]
    public string? two_factor_secret { get; set; }

    /// <summary>
    /// 信任設備陣列：已信任的設備ID列表
    /// </summary>
    public List<string>? trusted_devices { get; set; }

    /// <summary>
    /// 信任IP陣列：已信任的IP地址列表
    /// </summary>
    public List<string>? trusted_ips { get; set; }

    /// <summary>
    /// 設備指紋陣列：設備唯一識別碼列表
    /// </summary>
    public List<string>? device_fingerprints { get; set; }

    /// <summary>
    /// 最後設備資訊：JSON格式的設備詳細資訊
    /// </summary>
    [Column(TypeName = "jsonb")]
    public string? last_device_info { get; set; }

    /// <summary>
    /// 安全問題：JSON格式的安全問題和答案
    /// </summary>
    [Column(TypeName = "jsonb")]
    public string? security_questions { get; set; }

    /// <summary>
    /// 訂閱產品：JSON格式的訂閱產品資訊
    /// </summary>
    [Column(TypeName = "jsonb")]
    public string? subscription_products { get; set; }

    /// <summary>
    /// 付款方式：JSON格式的付款方式資訊
    /// </summary>
    [Column(TypeName = "jsonb")]
    public string? payment_methods { get; set; }

    /// <summary>
    /// 訂閱狀態：active/inactive/cancelled等
    /// </summary>
    [StringLength(50)]
    public string? subscription_status { get; set; }

    /// <summary>
    /// 訂閱到期時間：訂閱服務到期日期
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? subscription_expires_at { get; set; }

    /// <summary>
    /// 試用期結束時間：免費試用結束日期
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? trial_ends_at { get; set; }

    /// <summary>
    /// 計費週期：monthly/yearly等
    /// </summary>
    [StringLength(20)]
    public string? billing_cycle { get; set; }

    /// <summary>
    /// 自動續費：true=自動續費, false=手動續費
    /// </summary>
    public bool? auto_renew { get; set; }

    /// <summary>
    /// 用戶偏好：JSON格式的個人偏好設定
    /// </summary>
    [Column(TypeName = "jsonb")]
    public string? preferences { get; set; }

    /// <summary>
    /// 通知設定：JSON格式的通知偏好設定
    /// </summary>
    [Column(TypeName = "jsonb")]
    public string? notification_settings { get; set; }

    /// <summary>
    /// 隱私設定：JSON格式的隱私控制設定
    /// </summary>
    [Column(TypeName = "jsonb")]
    public string? privacy_settings { get; set; }

    /// <summary>
    /// 語言設定：用戶介面語言
    /// </summary>
    [StringLength(10)]
    public string? language { get; set; }

    /// <summary>
    /// 主題設定：用戶介面主題
    /// </summary>
    [StringLength(20)]
    public string? theme { get; set; }

    /// <summary>
    /// 登入次數：用戶總登入次數
    /// </summary>
    public int? login_count { get; set; }

    /// <summary>
    /// 最後登入時間：最近一次登入時間
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? last_login_at { get; set; }

    /// <summary>
    /// 最後活動時間：最近一次活動時間
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? last_activity_at { get; set; }

    /// <summary>
    /// 總會話時間：用戶累計使用時間
    /// </summary>
    public TimeSpan? total_session_time { get; set; }

    /// <summary>
    /// 資料完成度：個人資料完成百分比
    /// </summary>
    public int? profile_completion_percentage { get; set; }

    /// <summary>
    /// 上級ID：用戶=所屬組織ID, 角色=所屬組織ID, 組織=上級組織ID
    /// </summary>
    public List<string>? parent_id { get; set; }

    /// <summary>
    /// 排序順序：顯示順序編號
    /// </summary>
    public int? sort_order { get; set; }

    /// <summary>
    /// 層級：組織=組織層級(1-10), 角色=角色層級, 用戶=用戶層級
    /// </summary>
    public int? level { get; set; }

    /// <summary>
    /// 權限陣列：具體功能權限列表
    /// </summary>
    public List<string>? permissions { get; set; }

    /// <summary>
    /// 角色ID陣列：用戶=擁有的角色ID列表, 組織=分配的角色ID列表
    /// </summary>
    public List<string>? roles { get; set; }

    /// <summary>
    /// 是否啟用：true=啟用, false=停用
    /// </summary>
    public bool? is_active { get; set; }

    /// <summary>
    /// 是否在線：true=在線, false=離線
    /// </summary>
    public bool? is_online { get; set; }

    /// <summary>
    /// 狀態：active/inactive/suspended等
    /// </summary>
    [StringLength(50)]
    public string? status { get; set; }

    /// <summary>
    /// 狀態原因：狀態變更的原因說明
    /// </summary>
    public string? status_reason { get; set; }

    /// <summary>
    /// 建立時間：記錄建立時間
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? created_at { get; set; }

    /// <summary>
    /// 更新時間：記錄最後更新時間
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? updated_at { get; set; }

    /// <summary>
    /// 最後密碼變更時間：密碼最後修改時間
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? last_password_change_at { get; set; }

    /// <summary>
    /// 密碼到期時間：密碼過期日期
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? password_expires_at { get; set; }

    /// <summary>
    /// 建立者ID：建立此記錄的用戶ID
    /// </summary>
    public int? created_by { get; set; }

    /// <summary>
    /// 更新者ID：最後更新此記錄的用戶ID
    /// </summary>
    public int? updated_by { get; set; }

    /// <summary>
    /// 最後登入IP：最近一次登入的IP地址
    /// </summary>
    public IPAddress? last_login_ip { get; set; }

    /// <summary>
    /// 最後登入用戶代理：最近一次登入的瀏覽器資訊
    /// </summary>
    public string? last_login_user_agent { get; set; }

    /// <summary>
    /// 標籤陣列：用於分類和搜尋的標籤列表
    /// </summary>
    public List<string>? tags { get; set; }

    /// <summary>
    /// 備註：公開備註資訊
    /// </summary>
    public string? notes { get; set; }

    /// <summary>
    /// 內部備註：僅管理員可見的內部備註
    /// </summary>
    public string? internal_notes { get; set; }

    /// <summary>
    /// 導航權限陣列：儲存sidebar_navigation表的code編號，用於控制用戶可訪問的頁面
    /// </summary>
    public List<string>? navigation_permissions { get; set; }

    /// <summary>
    /// 角色名稱陣列：角色名稱列表（用於顯示）
    /// </summary>
    public List<string>? role_names { get; set; }

    /// <summary>
    /// 組織名稱陣列：組織名稱列表（用於顯示）
    /// </summary>
    public List<string>? organization_names { get; set; }

    /// <summary>
    /// 用戶名稱陣列：組織=所屬用戶名稱列表, 角色=擁有此角色的用戶名稱列表
    /// </summary>
    public List<string>? user_names { get; set; }
}
