// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.HnbWeb;

[Table("team_member", Schema = "dbo")]
public partial class team_member
{
    [Key]
    public int id { get; set; }

    [StringLength(100)]
    public string name { get; set; } = null!;

    [StringLength(100)]
    public string role { get; set; } = null!;

    [StringLength(255)]
    public string? avatar_url { get; set; }

    [StringLength(4)]
    public string? avatar_text { get; set; }

    public string? bio { get; set; }

    public List<string>? skills { get; set; }

    [StringLength(7)]
    public string? color { get; set; }

    [StringLength(255)]
    public string? github { get; set; }

    [StringLength(255)]
    public string? linkedin { get; set; }

    [StringLength(255)]
    public string? twitter { get; set; }

    public bool? is_active { get; set; }
}
