// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Models.HnbBackoffice;

public partial class HnbBackofficeDbContext : DbContext
{
    public HnbBackofficeDbContext(DbContextOptions<HnbBackofficeDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<permission_management> permission_managements { get; set; }

    public virtual DbSet<sidebar_navigation> sidebar_navigations { get; set; }

    public virtual DbSet<vw_permission_organization> vw_permission_organizations { get; set; }

    public virtual DbSet<vw_permission_role> vw_permission_roles { get; set; }

    public virtual DbSet<vw_permission_user> vw_permission_users { get; set; }

    public virtual DbSet<vw_sidebar_navigation> vw_sidebar_navigations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("C")
            .HasPostgresExtension("dbo", "dblink");

        modelBuilder.Entity<permission_management>(entity =>
        {
            entity.HasKey(e => e.id).HasName("permission_management_pkey");

            entity.ToTable("permission_management", "dbo", tb => tb.HasComment("權限管理統一資料表 - 用於統一管理用戶、角色、組織三種類型的資料，透過 type 欄位區分資料類型"));

            entity.Property(e => e.id)
                .ValueGeneratedNever()
                .HasComment("主鍵ID");
            entity.Property(e => e.auto_renew).HasComment("自動續費：true=自動續費, false=手動續費");
            entity.Property(e => e.avatar_url).HasComment("頭像網址：用戶頭像圖片連結");
            entity.Property(e => e.billing_cycle).HasComment("計費週期：monthly/yearly等");
            entity.Property(e => e.bio).HasComment("個人簡介：用戶的自我介紹");
            entity.Property(e => e.birthday).HasComment("生日：用戶出生日期");
            entity.Property(e => e.color_scheme).HasComment("色彩主題：用戶介面色彩配置");
            entity.Property(e => e.created_at).HasComment("建立時間：記錄建立時間");
            entity.Property(e => e.created_by).HasComment("建立者ID：建立此記錄的用戶ID");
            entity.Property(e => e.description).HasComment("描述：角色或組織的詳細說明");
            entity.Property(e => e.device_fingerprints).HasComment("設備指紋陣列：設備唯一識別碼列表");
            entity.Property(e => e.email).HasComment("電子郵件：主要用於用戶登入和聯絡");
            entity.Property(e => e.favorite_color).HasComment("喜愛的顏色：用戶偏好顏色");
            entity.Property(e => e.full_name).HasComment("完整名稱：用戶=真實姓名, 角色=角色完整名稱, 組織=組織完整名稱");
            entity.Property(e => e.gender).HasComment("性別：男/女/其他");
            entity.Property(e => e.internal_notes).HasComment("內部備註：僅管理員可見的內部備註");
            entity.Property(e => e.is_active).HasComment("是否啟用：true=啟用, false=停用");
            entity.Property(e => e.is_email_verified).HasComment("郵箱是否驗證：true=已驗證, false=未驗證");
            entity.Property(e => e.is_online).HasComment("是否在線：true=在線, false=離線");
            entity.Property(e => e.is_phone_verified).HasComment("電話是否驗證：true=已驗證, false=未驗證");
            entity.Property(e => e.language).HasComment("語言設定：用戶介面語言");
            entity.Property(e => e.last_activity_at).HasComment("最後活動時間：最近一次活動時間");
            entity.Property(e => e.last_device_info).HasComment("最後設備資訊：JSON格式的設備詳細資訊");
            entity.Property(e => e.last_login_at).HasComment("最後登入時間：最近一次登入時間");
            entity.Property(e => e.last_login_ip).HasComment("最後登入IP：最近一次登入的IP地址");
            entity.Property(e => e.last_login_user_agent).HasComment("最後登入用戶代理：最近一次登入的瀏覽器資訊");
            entity.Property(e => e.last_password_change_at).HasComment("最後密碼變更時間：密碼最後修改時間");
            entity.Property(e => e.level).HasComment("層級：組織=組織層級(1-10), 角色=角色層級, 用戶=用戶層級");
            entity.Property(e => e.location).HasComment("所在地：用戶居住或工作地點");
            entity.Property(e => e.login_count).HasComment("登入次數：用戶總登入次數");
            entity.Property(e => e.login_method).HasComment("登入方式：local/oauth/google/facebook等");
            entity.Property(e => e.name).HasComment("名稱：用戶=username, 角色=角色名稱, 組織=組織名稱");
            entity.Property(e => e.navigation_permissions).HasComment("導航權限陣列：儲存sidebar_navigation表的code編號，用於控制用戶可訪問的頁面");
            entity.Property(e => e.nickname).HasComment("暱稱：用戶的顯示暱稱");
            entity.Property(e => e.notes).HasComment("備註：公開備註資訊");
            entity.Property(e => e.notification_settings).HasComment("通知設定：JSON格式的通知偏好設定");
            entity.Property(e => e.organization_names).HasComment("組織名稱陣列：組織名稱列表（用於顯示）");
            entity.Property(e => e.parent_id).HasComment("上級ID：用戶=所屬組織ID, 角色=所屬組織ID, 組織=上級組織ID");
            entity.Property(e => e.password_expires_at).HasComment("密碼到期時間：密碼過期日期");
            entity.Property(e => e.password_hash).HasComment("密碼雜湊值：用於用戶密碼驗證");
            entity.Property(e => e.payment_methods).HasComment("付款方式：JSON格式的付款方式資訊");
            entity.Property(e => e.permissions).HasComment("權限陣列：具體功能權限列表");
            entity.Property(e => e.phone).HasComment("電話號碼：用戶聯絡電話");
            entity.Property(e => e.preferences).HasComment("用戶偏好：JSON格式的個人偏好設定");
            entity.Property(e => e.privacy_settings).HasComment("隱私設定：JSON格式的隱私控制設定");
            entity.Property(e => e.profile_completion_percentage).HasComment("資料完成度：個人資料完成百分比");
            entity.Property(e => e.role_names).HasComment("角色名稱陣列：角色名稱列表（用於顯示）");
            entity.Property(e => e.roles).HasComment("角色ID陣列：用戶=擁有的角色ID列表, 組織=分配的角色ID列表");
            entity.Property(e => e.salt).HasComment("密碼鹽值：用於密碼雜湊的隨機字串");
            entity.Property(e => e.security_questions).HasComment("安全問題：JSON格式的安全問題和答案");
            entity.Property(e => e.sort_order).HasComment("排序順序：顯示順序編號");
            entity.Property(e => e.status).HasComment("狀態：active/inactive/suspended等");
            entity.Property(e => e.status_reason).HasComment("狀態原因：狀態變更的原因說明");
            entity.Property(e => e.subscription_expires_at).HasComment("訂閱到期時間：訂閱服務到期日期");
            entity.Property(e => e.subscription_products).HasComment("訂閱產品：JSON格式的訂閱產品資訊");
            entity.Property(e => e.subscription_status).HasComment("訂閱狀態：active/inactive/cancelled等");
            entity.Property(e => e.tags).HasComment("標籤陣列：用於分類和搜尋的標籤列表");
            entity.Property(e => e.theme).HasComment("主題設定：用戶介面主題");
            entity.Property(e => e.third_party_avatar).HasComment("第三方頭像：第三方登入的頭像網址");
            entity.Property(e => e.third_party_email).HasComment("第三方郵箱：第三方登入的郵箱地址");
            entity.Property(e => e.third_party_id).HasComment("第三方ID：OAuth等第三方登入的用戶ID");
            entity.Property(e => e.timezone).HasComment("時區：用戶所在時區");
            entity.Property(e => e.total_session_time).HasComment("總會話時間：用戶累計使用時間");
            entity.Property(e => e.trial_ends_at).HasComment("試用期結束時間：免費試用結束日期");
            entity.Property(e => e.trusted_devices).HasComment("信任設備陣列：已信任的設備ID列表");
            entity.Property(e => e.trusted_ips).HasComment("信任IP陣列：已信任的IP地址列表");
            entity.Property(e => e.two_factor_enabled).HasComment("是否啟用雙因子認證：true=啟用, false=未啟用");
            entity.Property(e => e.two_factor_secret).HasComment("雙因子認證密鑰：TOTP密鑰");
            entity.Property(e => e.type).HasComment("資料類型：user=用戶, role=角色, organization=組織");
            entity.Property(e => e.updated_at).HasComment("更新時間：記錄最後更新時間");
            entity.Property(e => e.updated_by).HasComment("更新者ID：最後更新此記錄的用戶ID");
            entity.Property(e => e.user_names).HasComment("用戶名稱陣列：組織=所屬用戶名稱列表, 角色=擁有此角色的用戶名稱列表");
            entity.Property(e => e.zodiac_sign).HasComment("星座：用戶星座");
        });

        modelBuilder.Entity<sidebar_navigation>(entity =>
        {
            entity.HasKey(e => e.id).HasName("sidebar_navigation_pkey");

            entity.ToTable("sidebar_navigation", "dbo", tb => tb.HasComment("側欄導航管理表"));

            entity.Property(e => e.id)
                .HasComment("主鍵，自動遞增")
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(25L, null, null, null, null, null);
            entity.Property(e => e.code).HasComment("導航項目編號，唯一識別碼");
            entity.Property(e => e.created_at).HasComment("建立時間");
            entity.Property(e => e.icon).HasComment("導航項目圖示名稱");
            entity.Property(e => e.is_active).HasComment("是否啟用此導航項目");
            entity.Property(e => e.parent_code).HasComment("父級導航項目編號，用於建立階層結構");
            entity.Property(e => e.sort_order).HasComment("排序順序，數字越小越前面");
            entity.Property(e => e.title).HasComment("導航項目顯示標題");
            entity.Property(e => e.updated_at).HasComment("最後更新時間");
            entity.Property(e => e.url).HasComment("導航項目連結網址");
        });

        modelBuilder.Entity<vw_permission_organization>(entity =>
        {
            entity.ToView("vw_permission_organization", "dbo");

            entity.Property(e => e.created_at).HasComment("建立時間");
            entity.Property(e => e.created_by).HasComment("建立者ID");
            entity.Property(e => e.id).HasComment("主鍵ID");
            entity.Property(e => e.internal_notes).HasComment("內部備註");
            entity.Property(e => e.is_active).HasComment("是否啟用");
            entity.Property(e => e.is_root_organization).HasComment("是否為根組織");
            entity.Property(e => e.organization_description).HasComment("組織描述");
            entity.Property(e => e.organization_level).HasComment("組織層級");
            entity.Property(e => e.organization_name).HasComment("組織名稱");
            entity.Property(e => e.organization_role_ids).HasComment("組織角色ID陣列");
            entity.Property(e => e.organization_role_names).HasComment("組織角色名稱陣列");
            entity.Property(e => e.organization_user_full_names).HasComment("組織用戶完整名稱陣列");
            entity.Property(e => e.organization_user_ids).HasComment("組織用戶ID陣列");
            entity.Property(e => e.organization_user_names).HasComment("組織用戶名稱陣列");
            entity.Property(e => e.parent_id).HasComment("上級組織ID");
            entity.Property(e => e.parent_organization_id).HasComment("上級組織ID");
            entity.Property(e => e.parent_organization_name).HasComment("上級組織名稱");
            entity.Property(e => e.public_notes).HasComment("公開備註");
            entity.Property(e => e.sort_order).HasComment("排序順序");
            entity.Property(e => e.status).HasComment("狀態");
            entity.Property(e => e.sub_organization_ids).HasComment("子組織ID陣列");
            entity.Property(e => e.sub_organization_names).HasComment("子組織名稱陣列");
            entity.Property(e => e.total_organization_members_count).HasComment("組織成員總數");
            entity.Property(e => e.total_roles_count).HasComment("總角色數量");
            entity.Property(e => e.total_sub_organizations_count).HasComment("總子組織數量");
            entity.Property(e => e.total_users_count).HasComment("總用戶數量");
            entity.Property(e => e.type).HasComment("資料類型：organization");
            entity.Property(e => e.updated_at).HasComment("更新時間");
            entity.Property(e => e.updated_by).HasComment("更新者ID");
        });

        modelBuilder.Entity<vw_permission_role>(entity =>
        {
            entity.ToView("vw_permission_role", "dbo");

            entity.Property(e => e.created_at).HasComment("建立時間");
            entity.Property(e => e.created_by).HasComment("建立者ID");
            entity.Property(e => e.description).HasComment("角色描述");
            entity.Property(e => e.id).HasComment("主鍵ID");
            entity.Property(e => e.internal_notes).HasComment("內部備註");
            entity.Property(e => e.is_active).HasComment("是否啟用");
            entity.Property(e => e.is_system_role).HasComment("是否為系統角色");
            entity.Property(e => e.level).HasComment("角色層級");
            entity.Property(e => e.name).HasComment("角色名稱");
            entity.Property(e => e.navigation_permissions).HasComment("導航權限陣列");
            entity.Property(e => e.notes).HasComment("備註");
            entity.Property(e => e.organization_id).HasComment("所屬組織ID");
            entity.Property(e => e.organization_name).HasComment("所屬組織名稱");
            entity.Property(e => e.parent_id).HasComment("所屬組織ID");
            entity.Property(e => e.permission_count).HasComment("權限數量");
            entity.Property(e => e.permission_names).HasComment("權限名稱陣列");
            entity.Property(e => e.permissions).HasComment("權限陣列");
            entity.Property(e => e.role_type).HasComment("角色類型：system/custom");
            entity.Property(e => e.sort_order).HasComment("排序順序");
            entity.Property(e => e.status).HasComment("狀態");
            entity.Property(e => e.tags).HasComment("標籤陣列");
            entity.Property(e => e.type).HasComment("資料類型：role");
            entity.Property(e => e.updated_at).HasComment("更新時間");
            entity.Property(e => e.updated_by).HasComment("更新者ID");
            entity.Property(e => e.user_count).HasComment("擁有此角色的用戶數量");
            entity.Property(e => e.user_names).HasComment("擁有此角色的用戶名稱陣列");
        });

        modelBuilder.Entity<vw_permission_user>(entity =>
        {
            entity.ToView("vw_permission_user", "dbo");

            entity.Property(e => e.assigned_roles_count).HasComment("分配的角色數量：從roles陣列長度計算");
            entity.Property(e => e.auto_renew).HasComment("自動續費");
            entity.Property(e => e.avatar_url).HasComment("頭像網址");
            entity.Property(e => e.billing_cycle).HasComment("計費週期");
            entity.Property(e => e.bio).HasComment("個人簡介");
            entity.Property(e => e.birthday).HasComment("生日");
            entity.Property(e => e.child_organizations_count).HasComment("管理的子組織數量：該用戶管理的子組織數量");
            entity.Property(e => e.color_scheme).HasComment("色彩主題");
            entity.Property(e => e.created_at).HasComment("建立時間");
            entity.Property(e => e.created_by).HasComment("建立者ID");
            entity.Property(e => e.email).HasComment("電子郵件");
            entity.Property(e => e.favorite_color).HasComment("喜愛的顏色");
            entity.Property(e => e.full_name).HasComment("完整名稱");
            entity.Property(e => e.gender).HasComment("性別");
            entity.Property(e => e.id).HasComment("主鍵ID");
            entity.Property(e => e.internal_notes).HasComment("內部備註");
            entity.Property(e => e.is_active).HasComment("是否啟用");
            entity.Property(e => e.is_email_verified).HasComment("郵箱是否驗證");
            entity.Property(e => e.is_online).HasComment("是否在線");
            entity.Property(e => e.is_phone_verified).HasComment("電話是否驗證");
            entity.Property(e => e.language).HasComment("語言設定");
            entity.Property(e => e.last_activity_at).HasComment("最後活動時間");
            entity.Property(e => e.last_device_info).HasComment("最後設備資訊");
            entity.Property(e => e.last_login_at).HasComment("最後登入時間");
            entity.Property(e => e.last_login_days_ago).HasComment("距離上次登入天數：計算欄位");
            entity.Property(e => e.last_login_ip).HasComment("最後登入IP");
            entity.Property(e => e.last_login_user_agent).HasComment("最後登入用戶代理");
            entity.Property(e => e.last_password_change_at).HasComment("最後密碼變更時間");
            entity.Property(e => e.level).HasComment("用戶層級");
            entity.Property(e => e.location).HasComment("所在地");
            entity.Property(e => e.login_count).HasComment("登入次數");
            entity.Property(e => e.login_method).HasComment("登入方式");
            entity.Property(e => e.name).HasComment("用戶名稱：從name欄位取得");
            entity.Property(e => e.nickname).HasComment("暱稱");
            entity.Property(e => e.notes).HasComment("備註");
            entity.Property(e => e.notification_settings).HasComment("通知設定");
            entity.Property(e => e.organization_id).HasComment("所屬組織ID：從parent_id取得");
            entity.Property(e => e.organization_name).HasComment("所屬組織名稱：從parent_id關聯取得");
            entity.Property(e => e.parent_id).HasComment("所屬組織ID");
            entity.Property(e => e.password_expires_at).HasComment("密碼到期時間");
            entity.Property(e => e.password_hash).HasComment("密碼雜湊值");
            entity.Property(e => e.payment_methods).HasComment("付款方式");
            entity.Property(e => e.permissions).HasComment("權限陣列");
            entity.Property(e => e.phone).HasComment("電話號碼");
            entity.Property(e => e.preferences).HasComment("用戶偏好");
            entity.Property(e => e.privacy_settings).HasComment("隱私設定");
            entity.Property(e => e.profile_completion_percentage).HasComment("資料完成度");
            entity.Property(e => e.role_ids).HasComment("角色ID陣列：從roles欄位解析");
            entity.Property(e => e.role_name).HasComment("主要角色名稱：從roles陣列取得第一個角色名稱");
            entity.Property(e => e.roles).HasComment("角色ID陣列");
            entity.Property(e => e.salt).HasComment("密碼鹽值");
            entity.Property(e => e.sort_order).HasComment("排序順序");
            entity.Property(e => e.status).HasComment("狀態");
            entity.Property(e => e.status_reason).HasComment("狀態原因");
            entity.Property(e => e.subscription_expires_at).HasComment("訂閱到期時間");
            entity.Property(e => e.subscription_products).HasComment("訂閱產品");
            entity.Property(e => e.subscription_status).HasComment("訂閱狀態");
            entity.Property(e => e.tags).HasComment("標籤陣列");
            entity.Property(e => e.theme).HasComment("主題設定");
            entity.Property(e => e.third_party_avatar).HasComment("第三方頭像");
            entity.Property(e => e.third_party_id).HasComment("第三方ID");
            entity.Property(e => e.timezone).HasComment("時區");
            entity.Property(e => e.total_session_time).HasComment("總會話時間");
            entity.Property(e => e.trial_ends_at).HasComment("試用期結束時間");
            entity.Property(e => e.trusted_devices).HasComment("信任設備陣列");
            entity.Property(e => e.trusted_ips).HasComment("信任IP陣列");
            entity.Property(e => e.two_factor_enabled).HasComment("是否啟用雙因子認證");
            entity.Property(e => e.type).HasComment("資料類型：user");
            entity.Property(e => e.updated_at).HasComment("更新時間");
            entity.Property(e => e.updated_by).HasComment("更新者ID");
            entity.Property(e => e.zodiac_sign).HasComment("星座");
        });

        modelBuilder.Entity<vw_sidebar_navigation>(entity =>
        {
            entity.ToView("vw_sidebar_navigation", "dbo");

            entity.Property(e => e.children).HasComment("子項目陣列：子導航項目的code陣列");
            entity.Property(e => e.children_count).HasComment("子項目數量：自動計算子導航項目數量");
            entity.Property(e => e.code).HasComment("導航項目編號");
            entity.Property(e => e.created_at).HasComment("建立時間");
            entity.Property(e => e.full_path).HasComment("完整路徑：階層路徑字串");
            entity.Property(e => e.hierarchy_level).HasComment("階層等級：1為根項目，2為子項目");
            entity.Property(e => e.icon).HasComment("導航項目圖示");
            entity.Property(e => e.id).HasComment("主鍵ID");
            entity.Property(e => e.is_active).HasComment("是否啟用");
            entity.Property(e => e.is_leaf).HasComment("是否為葉子節點：children_count = 0時為true");
            entity.Property(e => e.is_parent).HasComment("是否有子項目：children_count > 0時為true");
            entity.Property(e => e.parent_code).HasComment("父級導航項目編號");
            entity.Property(e => e.parent_title).HasComment("父級導航標題：從parent_code關聯取得");
            entity.Property(e => e.sort_order).HasComment("排序順序");
            entity.Property(e => e.title).HasComment("導航項目標題");
            entity.Property(e => e.updated_at).HasComment("更新時間");
            entity.Property(e => e.url).HasComment("導航項目連結");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
