// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.HnbBackoffice;

[Keyless]
public partial class vw_permission_role
{
    /// <summary>
    /// 主鍵ID
    /// </summary>
    public int? id { get; set; }

    /// <summary>
    /// 資料類型：role
    /// </summary>
    [StringLength(50)]
    public string? type { get; set; }

    /// <summary>
    /// 角色名稱
    /// </summary>
    [StringLength(100)]
    public string? name { get; set; }

    /// <summary>
    /// 角色描述
    /// </summary>
    [StringLength(500)]
    public string? description { get; set; }

    /// <summary>
    /// 權限陣列
    /// </summary>
    public List<string>? permissions { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool? is_active { get; set; }

    /// <summary>
    /// 狀態
    /// </summary>
    [StringLength(50)]
    public string? status { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? created_at { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? updated_at { get; set; }

    /// <summary>
    /// 標籤陣列
    /// </summary>
    public List<string>? tags { get; set; }

    /// <summary>
    /// 備註
    /// </summary>
    public string? notes { get; set; }

    /// <summary>
    /// 所屬組織ID
    /// </summary>
    public int? parent_id { get; set; }

    /// <summary>
    /// 排序順序
    /// </summary>
    public int? sort_order { get; set; }

    /// <summary>
    /// 角色層級
    /// </summary>
    public int? level { get; set; }

    /// <summary>
    /// 建立者ID
    /// </summary>
    public int? created_by { get; set; }

    /// <summary>
    /// 更新者ID
    /// </summary>
    public int? updated_by { get; set; }

    /// <summary>
    /// 內部備註
    /// </summary>
    public string? internal_notes { get; set; }

    /// <summary>
    /// 所屬組織名稱
    /// </summary>
    [StringLength(100)]
    public string? organization_name { get; set; }

    /// <summary>
    /// 所屬組織ID
    /// </summary>
    public int? organization_id { get; set; }

    /// <summary>
    /// 擁有此角色的用戶數量
    /// </summary>
    public long? user_count { get; set; }

    /// <summary>
    /// 權限數量
    /// </summary>
    public int? permission_count { get; set; }

    /// <summary>
    /// 擁有此角色的用戶名稱陣列
    /// </summary>
    [Column(TypeName = "character varying[]")]
    public List<string>? user_names { get; set; }

    /// <summary>
    /// 導航權限陣列
    /// </summary>
    public List<string>? navigation_permissions { get; set; }

    /// <summary>
    /// 權限名稱陣列
    /// </summary>
    [Column(TypeName = "character varying[]")]
    public List<string>? permission_names { get; set; }

    /// <summary>
    /// 角色類型：system/custom
    /// </summary>
    public string? role_type { get; set; }

    /// <summary>
    /// 是否為系統角色
    /// </summary>
    public bool? is_system_role { get; set; }
}
