// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HNB.IIS.Core.Models;

[Table("access_records", Schema = "dbo")]
public partial class access_record
{
    [Key]
    public Guid id { get; set; }

    public string user_name { get; set; } = null!;

    public string? roles { get; set; }

    public string request_path { get; set; } = null!;

    public string? ip { get; set; }

    public string result { get; set; } = null!;

    public string? user_agent { get; set; }

    public DateTime? created_at { get; set; }

    public string? log_type { get; set; }

    public string? http_method { get; set; }

    public string? request_body { get; set; }

    public string? response_body { get; set; }

    public int? status_code { get; set; }

    public double? duration_ms { get; set; }
}
