// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Models.HnbWeb;

public partial class HnbWebDbContext : DbContext
{
    public HnbWebDbContext(DbContextOptions<HnbWebDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<project> projects { get; set; }

    public virtual DbSet<project_tag> project_tags { get; set; }

    public virtual DbSet<team_member> team_members { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("C");

        modelBuilder.Entity<project_tag>(entity =>
        {
            entity.HasKey(e => e.id).HasName("project_tags_pkey");

            entity.Property(e => e.code).HasDefaultValueSql("''::character varying");
            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
            entity.Property(e => e.updated_at).HasDefaultValueSql("now()");
        });

        modelBuilder.Entity<team_member>(entity =>
        {
            entity.HasKey(e => e.id).HasName("team_member_pkey");

            entity.Property(e => e.is_active).HasDefaultValue(true);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
