// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.HnbWeb;

[Keyless]
[Table("project", Schema = "dbo")]
public partial class project
{
    public int id { get; set; }

    [StringLength(100)]
    public string category { get; set; } = null!;

    [StringLength(200)]
    public string name { get; set; } = null!;

    [StringLength(255)]
    public string? icon { get; set; }

    public string? summary { get; set; }

    public List<string>? highlight { get; set; }

    public List<string>? features { get; set; }

    public List<string>? screenshots { get; set; }

    public string? intro { get; set; }

    public List<string>? challenges { get; set; }

    public List<string>? solution { get; set; }

    [StringLength(50)]
    public string? duration { get; set; }

    public int? team_size { get; set; }

    [StringLength(200)]
    public string? client { get; set; }

    [StringLength(50)]
    public string? status { get; set; }

    public List<string>? tech_stack { get; set; }

    public string? main_features { get; set; }

    public List<string>? feature_intro { get; set; }

    public List<string>? dev_tools { get; set; }

    [StringLength(255)]
    public string? arch_img { get; set; }

    public string? outcome_summary { get; set; }

    public string? outcome_performance { get; set; }

    [StringLength(1000)]
    public string? feedback { get; set; }

    [StringLength(50)]
    public string? icon_color { get; set; }
}
