// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.HnbBackoffice;

/// <summary>
/// 側欄導航管理表
/// </summary>
[Keyless]
[Table("sidebar_navigation", Schema = "dbo")]
public partial class sidebar_navigation
{
    /// <summary>
    /// 主鍵，自動遞增
    /// </summary>
    public int? id { get; set; }

    /// <summary>
    /// 導航項目編號，唯一識別碼
    /// </summary>
    [StringLength(50)]
    public string? code { get; set; }

    /// <summary>
    /// 導航項目顯示標題
    /// </summary>
    [StringLength(100)]
    public string? title { get; set; }

    /// <summary>
    /// 導航項目連結網址
    /// </summary>
    [StringLength(500)]
    public string? url { get; set; }

    /// <summary>
    /// 導航項目圖示名稱
    /// </summary>
    [StringLength(50)]
    public string? icon { get; set; }

    /// <summary>
    /// 排序順序，數字越小越前面
    /// </summary>
    public int? sort_order { get; set; }

    /// <summary>
    /// 父級導航項目編號，用於建立階層結構
    /// </summary>
    [StringLength(50)]
    public string? parent_code { get; set; }

    /// <summary>
    /// 是否啟用此導航項目
    /// </summary>
    public bool? is_active { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime? created_at { get; set; }

    /// <summary>
    /// 最後更新時間
    /// </summary>
    public DateTime? updated_at { get; set; }
}
