// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.Hnbdata;

/// <summary>
/// ProjectTags（畫面 icon 專區）
/// </summary>
[Table("project_tags", Schema = "dbo")]
[Index("category", Name = "project_tags_category_key", IsUnique = true)]
public partial class project_tag
{
    [Key]
    public int id { get; set; }

    /// <summary>
    /// 專案大類（例如 手機APP、軟體系統、Web系統）
    /// </summary>
    [StringLength(100)]
    public string category { get; set; } = null!;

    /// <summary>
    /// 專案大類 icon 名稱
    /// </summary>
    [StringLength(255)]
    public string? icon { get; set; }

    /// <summary>
    /// 專案大類 icon 顏色 (#HEX 或文字)
    /// </summary>
    [StringLength(50)]
    public string? icon_color { get; set; }

    /// <summary>
    /// 創建時間
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime created_at { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime updated_at { get; set; }

    [StringLength(50)]
    public string code { get; set; } = null!;
}
