// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.HnbHnbBackoffice;

[Table("ai_config", Schema = "dbo")]
[Index("deleted_at", Name = "idx_ai_config_deleted_at")]
[Index("is_enabled", Name = "idx_ai_config_enabled")]
[Index("provider", Name = "idx_ai_config_provider")]
[Index("scope", Name = "idx_ai_config_scope")]
public partial class ai_config
{
    [Key]
    public long id { get; set; }

    [StringLength(100)]
    public string service_name { get; set; } = null!;

    [StringLength(50)]
    public string provider { get; set; } = null!;

    [StringLength(50)]
    public string scope { get; set; } = null!;

    [StringLength(100)]
    public string model_key { get; set; } = null!;

    [StringLength(20)]
    public string? version { get; set; }

    public string? description { get; set; }

    public string? changelog { get; set; }

    public string? system_prompt { get; set; }

    public List<string>? field_names { get; set; }

    public List<string>? field_labels { get; set; }

    public List<string>? field_types { get; set; }

    public List<string>? field_values { get; set; }

    public List<bool>? field_required { get; set; }

    public List<bool>? field_sensitive { get; set; }

    public List<bool>? field_enabled { get; set; }

    [Precision(3, 2)]
    public decimal? quality_score { get; set; }

    [Precision(10, 2)]
    public decimal? monthly_budget { get; set; }

    [Precision(10, 2)]
    public decimal? yearly_budget { get; set; }

    public int? budget_alert_threshold { get; set; }

    public bool is_enabled { get; set; }

    public int priority { get; set; }

    public int? daily_limit { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime created_at { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? updated_at { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? deleted_at { get; set; }

    [InverseProperty("ai_config")]
    public virtual ICollection<ai_log> ai_logs { get; set; } = new List<ai_log>();
}
