// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.HnbHnbBackoffice;

[Table("ai_log", Schema = "dbo")]
[Index("ai_config_id", Name = "idx_ai_log_config_id")]
[Index("created_at", Name = "idx_ai_log_created_at", AllDescending = true)]
[Index("request_type", Name = "idx_ai_log_request_type")]
[Index("status", Name = "idx_ai_log_status")]
[Index("user_id", Name = "idx_ai_log_user_id")]
public partial class ai_log
{
    [Key]
    public long id { get; set; }

    public long ai_config_id { get; set; }

    public int? user_id { get; set; }

    [StringLength(50)]
    public string request_type { get; set; } = null!;

    [Column(TypeName = "jsonb")]
    public string? request_data { get; set; }

    [Column(TypeName = "jsonb")]
    public string? response_data { get; set; }

    [StringLength(20)]
    public string status { get; set; } = null!;

    public int? response_time_ms { get; set; }

    public int? tokens_used { get; set; }

    [Precision(10, 4)]
    public decimal? cost { get; set; }

    public string? error_message { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime created_at { get; set; }

    [ForeignKey("ai_config_id")]
    [InverseProperty("ai_logs")]
    public virtual ai_config ai_config { get; set; } = null!;
}
