// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.HnbHnbBackoffice;

/// <summary>
/// 檔案管理資料表
/// </summary>
[Table("file_manager", Schema = "dbo")]
[Index("code", Name = "file_manager_code_key", IsUnique = true)]
[Index("code", Name = "idx_code")]
[Index("mode", Name = "idx_file_manager_mode")]
[Index("is_deleted", Name = "idx_is_deleted")]
[Index("item_type", Name = "idx_item_type")]
[Index("owner_username", Name = "idx_owner")]
[Index("parent_code", Name = "idx_parent_code")]
public partial class file_manager
{
    /// <summary>
    /// 流水號主鍵
    /// </summary>
    [Key]
    public long id { get; set; }

    /// <summary>
    /// 唯一識別碼
    /// </summary>
    [StringLength(100)]
    public string code { get; set; } = null!;

    /// <summary>
    /// 檔案或資料夾名稱
    /// </summary>
    [StringLength(500)]
    public string file_name { get; set; } = null!;

    /// <summary>
    /// 檔案路徑
    /// </summary>
    public string? file_path { get; set; }

    /// <summary>
    /// 共享使用者陣列
    /// </summary>
    public List<string>? shared_users { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? created_at { get; set; }

    /// <summary>
    /// 檔案大小（bytes）
    /// </summary>
    public long? file_size { get; set; }

    /// <summary>
    /// 上層資料夾 code
    /// </summary>
    [StringLength(100)]
    public string? parent_code { get; set; }

    /// <summary>
    /// 類型（file/folder）
    /// </summary>
    [StringLength(20)]
    public string item_type { get; set; } = null!;

    /// <summary>
    /// 擁有者使用者名稱
    /// </summary>
    [StringLength(100)]
    public string owner_username { get; set; } = null!;

    /// <summary>
    /// MIME 類型
    /// </summary>
    [StringLength(100)]
    public string? mime_type { get; set; }

    /// <summary>
    /// 是否已軟刪除
    /// </summary>
    public bool? is_deleted { get; set; }

    /// <summary>
    /// 刪除時間
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? deleted_at { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? updated_at { get; set; }

    /// <summary>
    /// 環境模式（development=開發區/測試區, production=正式區）
    /// </summary>
    [StringLength(20)]
    public string? mode { get; set; }
}
