// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.HnbHnbBackoffice;

[Keyless]
public partial class vw_ai_log
{
    public long? id { get; set; }

    public long? ai_config_id { get; set; }

    [StringLength(100)]
    public string? service_name { get; set; }

    [StringLength(50)]
    public string? provider { get; set; }

    [StringLength(50)]
    public string? scope { get; set; }

    [StringLength(100)]
    public string? model_key { get; set; }

    public int? user_id { get; set; }

    [StringLength(50)]
    public string? request_type { get; set; }

    [Column(TypeName = "jsonb")]
    public string? request_data { get; set; }

    [Column(TypeName = "jsonb")]
    public string? response_data { get; set; }

    [StringLength(20)]
    public string? status { get; set; }

    public int? tokens_used { get; set; }

    [Precision(10, 4)]
    public decimal? cost { get; set; }

    public int? response_time_ms { get; set; }

    public string? error_message { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? created_at { get; set; }

    public decimal? daily_cost { get; set; }

    public decimal? monthly_cost { get; set; }

    public decimal? budget_usage_percent { get; set; }
}
