// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.HnbHnbBackoffice;

[Keyless]
public partial class vw_file_manager
{
    public long? id { get; set; }

    [StringLength(100)]
    public string? code { get; set; }

    [StringLength(500)]
    public string? file_name { get; set; }

    public string? file_path { get; set; }

    public string? url { get; set; }

    public List<string>? shared_users { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? created_at { get; set; }

    public long? file_size { get; set; }

    [StringLength(100)]
    public string? parent_code { get; set; }

    [StringLength(20)]
    public string? item_type { get; set; }

    [StringLength(100)]
    public string? owner_username { get; set; }

    [StringLength(100)]
    public string? mime_type { get; set; }

    public bool? is_deleted { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? deleted_at { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? updated_at { get; set; }
}
