// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.HnbHnbBackoffice;

[Keyless]
public partial class vw_hardware_monitoring
{
    /// <summary>
    /// 主鍵ID
    /// </summary>
    public int? id { get; set; }

    /// <summary>
    /// 伺服器IP位址
    /// </summary>
    [StringLength(45)]
    public string? server_ip { get; set; }

    /// <summary>
    /// 伺服器位置
    /// </summary>
    [StringLength(100)]
    public string? server_location { get; set; }

    /// <summary>
    /// 伺服器提供商
    /// </summary>
    [StringLength(100)]
    public string? server_provider { get; set; }

    /// <summary>
    /// 環境類型
    /// </summary>
    [StringLength(50)]
    public string? environment_type { get; set; }

    /// <summary>
    /// 主機名稱
    /// </summary>
    [StringLength(100)]
    public string? host_name { get; set; }

    /// <summary>
    /// 作業系統
    /// </summary>
    [StringLength(100)]
    public string? operating_system { get; set; }

    /// <summary>
    /// 核心版本
    /// </summary>
    [StringLength(100)]
    public string? kernel_version { get; set; }

    /// <summary>
    /// 系統運行時間
    /// </summary>
    [StringLength(100)]
    public string? uptime { get; set; }

    /// <summary>
    /// CPU名稱
    /// </summary>
    public string? cpu_name { get; set; }

    /// <summary>
    /// CPU製造商
    /// </summary>
    public string? cpu_manufacturer { get; set; }

    /// <summary>
    /// CPU型號
    /// </summary>
    public string? cpu_model { get; set; }

    /// <summary>
    /// CPU核心數
    /// </summary>
    public int? cpu_cores { get; set; }

    /// <summary>
    /// CPU執行緒數
    /// </summary>
    public int? cpu_threads { get; set; }

    /// <summary>
    /// CPU基礎時脈 (GHz)
    /// </summary>
    public decimal? cpu_base_clock { get; set; }

    /// <summary>
    /// CPU加速時脈 (GHz)
    /// </summary>
    public decimal? cpu_boost_clock { get; set; }

    /// <summary>
    /// CPU溫度 (°C)
    /// </summary>
    public int? cpu_temperature { get; set; }

    /// <summary>
    /// CPU使用率 (%)
    /// </summary>
    public decimal? cpu_usage_percent { get; set; }

    /// <summary>
    /// CPU健康狀態
    /// </summary>
    public string? cpu_health_status { get; set; }

    /// <summary>
    /// CPU健康百分比
    /// </summary>
    public int? cpu_health_percentage { get; set; }

    /// <summary>
    /// GPU名稱
    /// </summary>
    public string? gpu_name { get; set; }

    /// <summary>
    /// GPU製造商
    /// </summary>
    public string? gpu_manufacturer { get; set; }

    /// <summary>
    /// GPU型號
    /// </summary>
    public string? gpu_model { get; set; }

    /// <summary>
    /// GPU記憶體大小
    /// </summary>
    public string? gpu_memory_size { get; set; }

    /// <summary>
    /// GPU溫度 (°C)
    /// </summary>
    public int? gpu_temperature { get; set; }

    /// <summary>
    /// GPU使用率 (%)
    /// </summary>
    public decimal? gpu_usage_percent { get; set; }

    /// <summary>
    /// GPU健康狀態
    /// </summary>
    public string? gpu_health_status { get; set; }

    /// <summary>
    /// GPU健康百分比
    /// </summary>
    public int? gpu_health_percentage { get; set; }

    /// <summary>
    /// 記憶體名稱
    /// </summary>
    public string? memory_name { get; set; }

    /// <summary>
    /// 記憶體類型
    /// </summary>
    public string? memory_type { get; set; }

    /// <summary>
    /// 記憶體總容量
    /// </summary>
    public string? memory_total_capacity { get; set; }

    /// <summary>
    /// 記憶體速度
    /// </summary>
    public string? memory_speed { get; set; }

    /// <summary>
    /// 記憶體使用率 (%)
    /// </summary>
    public decimal? memory_usage_percent { get; set; }

    /// <summary>
    /// 記憶體健康狀態
    /// </summary>
    public string? memory_health_status { get; set; }

    /// <summary>
    /// 記憶體健康百分比
    /// </summary>
    public int? memory_health_percentage { get; set; }

    /// <summary>
    /// 系統總記憶體 (bytes)
    /// </summary>
    public long? system_memory_total { get; set; }

    /// <summary>
    /// 系統已用記憶體 (bytes)
    /// </summary>
    public long? system_memory_used { get; set; }

    /// <summary>
    /// 系統可用記憶體 (bytes)
    /// </summary>
    public long? system_memory_free { get; set; }

    /// <summary>
    /// 記憶體總容量 (GB)
    /// </summary>
    public long? memory_total_capacity_gb { get; set; }

    /// <summary>
    /// 記憶體已使用 (GB)
    /// </summary>
    public long? memory_used_gb { get; set; }

    /// <summary>
    /// 記憶體可用 (GB)
    /// </summary>
    public long? memory_available_gb { get; set; }

    /// <summary>
    /// 系統負載平均值
    /// </summary>
    public decimal? system_load_avg { get; set; }

    /// <summary>
    /// 系統程序數
    /// </summary>
    public int? system_processes { get; set; }

    /// <summary>
    /// 系統使用者數
    /// </summary>
    public int? system_users { get; set; }

    /// <summary>
    /// 電池電量 (%)
    /// </summary>
    public int? battery_level { get; set; }

    /// <summary>
    /// 電源效率
    /// </summary>
    [StringLength(20)]
    public string? power_efficiency { get; set; }

    /// <summary>
    /// 電源供應器資訊
    /// </summary>
    public string? power_supply_info { get; set; }

    /// <summary>
    /// 最後檢查時間
    /// </summary>
    public DateTime? last_check_time { get; set; }

    /// <summary>
    /// 檢查方式
    /// </summary>
    [StringLength(50)]
    public string? check_method { get; set; }

    /// <summary>
    /// 檢查間隔 (秒)
    /// </summary>
    public int? check_interval { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool? is_active { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime? created_at { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    public DateTime? updated_at { get; set; }
}
