// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
// ╔════════════════════════════════════════════════════════════════════════╗
// ║                     嚴重警告 / CRITICAL WARNING                        ║
// ╠════════════════════════════════════════════════════════════════════════╣
// ║  此檔案為系統自動生成，禁止手動修改！                                    ║
// ║  This file is AUTO-GENERATED by the system. DO NOT MODIFY manually!    ║
// ║                                                                          ║
// ║  任何手動修改將在下次重新生成時被覆蓋且遺失！                            ║
// ║  Any manual changes will be OVERWRITTEN and LOST on next generation!   ║
// ║                                                                          ║
// ║  如需修改，請調整資料庫結構後重新執行 BuildModels 工具                   ║
// ║  To make changes, modify the database schema and re-run BuildModels     ║
// ╚════════════════════════════════════════════════════════════════════════╝
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.HnbHnbBackoffice;

[Keyless]
public partial class vw_permission_role
{
    public int? id { get; set; }

    [StringLength(50)]
    public string? type { get; set; }

    [StringLength(100)]
    public string? name { get; set; }

    [StringLength(500)]
    public string? description { get; set; }

    public List<string>? permissions { get; set; }

    public bool? is_active { get; set; }

    [StringLength(50)]
    public string? status { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? created_at { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? updated_at { get; set; }

    public List<string>? tags { get; set; }

    public string? notes { get; set; }

    public int? parent_id { get; set; }

    public int? sort_order { get; set; }

    public int? level { get; set; }

    public int? created_by { get; set; }

    public int? updated_by { get; set; }

    public string? internal_notes { get; set; }

    [StringLength(100)]
    public string? organization_name { get; set; }

    public int? organization_id { get; set; }

    public long? user_count { get; set; }

    public int? permission_count { get; set; }

    [Column(TypeName = "character varying[]")]
    public List<string>? user_names { get; set; }

    public List<string>? navigation_permissions { get; set; }

    public List<string>? permission_names { get; set; }

    [StringLength(50)]
    public string? role_type { get; set; }

    public bool? is_system_role { get; set; }
}
